[options]
admin_passwd = $pbkdf2-sha512$600000$yfn/31uLkdK6txaCECLkXA$F2ImIccZPgIMNsRGn78Z//vlNgbrUat0zD0XMu9wT4WqLDGwnKUAIvHxSwLa7OEPfK2e2s1.RlmlHSJz9Ro2yQ
db_host = localhost
db_port = 5432
db_user = odoo19dbuser
db_password = odoo19dbuser
addons_path = /Users/hussein/Desktop/Odoo19/odoo19/addons,/Users/hussein/Desktop/Odoo19/odoo19/custom_addons,/Users/hussein/Desktop/Odoo19/odoo19/custom_addons/muk_web_theme-19.0.1.4.0,/Users/hussein/Desktop/Odoo19/odoo19/custom_addons/om_account_accountant-19.0.1.0.3
http_port = 8019

